[mysql]
[mysql.base]
connmaxlifetime = 60
maxidleconn = 60
maxopenconn = 10

[mysql.log]
addr = "127.0.0.1:3306"
name = "iwut_log"
pass = "129028"
user = "iwut"
dsn = "iwut:129028@tcp(127.0.0.1:3306)/iwut_log?charset=utf8mb4&parseTime=True&loc=Local"

[redis]
addr = "127.0.0.1:6379"